# Generated by Django 5.2.1 on 2025-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_artigo_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='localizacao',
            field=models.PositiveIntegerField(blank=True, max_length=100),
        ),
    ]
