# Generated by Django 5.2.1 on 2025-06-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_artigo_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='localizacao',
            field=models.PositiveIntegerField(choices=[('Faro', 'Faro'), ('Quarteira', 'Quarteira'), ('Lagos', 'Lagos'), ('Lagoa', 'Lagoa'), ('Portimão', 'Portimão'), ('Albufeira', 'Albufeira'), ('Sagres', 'Sagres'), ('Aljez', 'Aljez'), ('Via Real de Santo António', 'Via Real de Santo António'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira'), ('Quarteira', 'Quarteira')], max_length=100),
        ),
    ]
