# Generated by Django 5.2.1 on 2025-06-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_artigo_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='localizacao',
            field=models.CharField(choices=[('Faro', 'Faro'), ('Quarteira', 'Quarteira'), ('Lagos', 'Lagos'), ('Lagoa', 'Lagoa'), ('Portimão', 'Portimão'), ('Albufeira', 'Albufeira'), ('Sagres', 'Sagres'), ('Aljez', 'Aljez'), ('Via Real de Santo António', 'Via Real de Santo António'), ('Olhão', 'Olhão'), ('Aljezur', 'Aljezur'), ('S. Teotónio', 'S. Teotónio'), ('Aljez', 'Aljez'), ('Ferreiras', 'Ferreiras'), ('Vidigueira', 'Vidigueira'), ('Barreiro', 'Barreiro'), ('Lisboa', 'Lisboa'), ('Estremoz', 'Estremoz'), ('Oeiras', 'Oeiras'), ('Alges', 'Alges'), ('Elvas', 'Elvas'), ('Amadora', 'Amadora'), ('Correia', 'Correia'), ('Carregado', 'Carregado'), ('Portalegre', 'Portalegre'), ('Santarém', 'Santanrém'), ('Castelo Branco', 'Castelo Branco'), ('Fundão', 'Fundão'), ('Coimbra', 'Coimbra'), ('Covilhã', 'Covilhã'), ('Catanhede', 'Catanhede'), ('Soito', 'Soito'), ('Guarda', 'Guarda'), ('Viseu', 'Viseu'), ('Figueira de Castelo Rodrigo', 'Figueira de Castelo Rodrigo'), ('Porto', 'Porto'), ('Amarante', 'Amarante'), ('Esposende', 'Esposende'), ('Vila do Conde', 'Vila do Conde')], max_length=100),
        ),
    ]
