# Generated by Django 5.2.1 on 2025-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='resposta_correta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
